// <auto-generated />
namespace FinalTerm_CNPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class finaltermdb_v5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(finaltermdb_v5));
        
        string IMigrationMetadata.Id
        {
            get { return "202010030722459_finaltermdb_v5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
